id: ID8628C17
legacy_id: P000452
ocr_import_info:
  bdrc_scan_id: W00KG02677
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T10:27:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:34:10.334328+00:00'
last_modified: 2022-08-30 21:35:17.410754
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG02677
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG02677
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡིད་བཞིན་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.5920313357910971
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I00KG02990:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02990
      total_pages: 570
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02990.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.5920313357910971
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
